# Generated by Django 2.1.5 on 2022-03-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePT109', '0006_finishedquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspiringQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InspiringQuoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='QuoteImage',
            new_name='ComedicQuote',
        ),
        migrations.RenameModel(
            old_name='Quote',
            new_name='ComedicQuoteImage',
        ),
    ]
