# Generated by Django 2.1.5 on 2022-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePT109', '0007_auto_20220328_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilisophicalQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PhilisophicalQuoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
