# Generated by Django 2.1.5 on 2022-03-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePT109', '0010_comedicprompt_inspiringprompt_philisophicalprompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
